---
- name: Cluster Prep
  hosts: k3s
  gather_facts: true
  become: true
  roles:

    - role: raspberrypi
#   - role: airgap
#    - role: prereq

- name: Setup K3S Server
  hosts: server
  become: true
  roles:
    - role: k3s_server

- name: Setup K3S agent
  hosts: agent
  become: true
  roles:
    - role: k3s_agent

- name: Setup Outside Cluster Tools
  hosts: server
  become: true
  roles:
    - role: outside_cluster_tools
    
#- name: Post-Install Tasks
#  become: true
#  roles:
#    - role: post_install
